### ISSUE TITLE
Test.sh aborted

### ISSUE THREAD

**Issue by kotabe-sh** [yokattame/SpindleNet#11]
Hi, we are trying to reproduce your learning system "spindle net" to 
compare our research, but we hit the error while doing test.sh. 
The learning processes by the scripts below looks successfully done.

    ./scripts/train_base.sh
    ./scripts/train_head.sh
    ./scripts/train_body.sh
    ./scripts/train_leg.sh
    ./scripts/train_rarm.sh
    ./scripts/train_larm.sh
    ./scripts/train_rleg.sh
    ./scripts/train_lleg.sh
    ./scripts/train_spindlenet.sh

But the "test.sh", I believe this is testing the result, died with the error.
Do you have any idea what cause this? or where should it be checked what happen?

Here is a log:

Extracting test_probe set
E0201 11:35:23.885982 10779 extract_features.cpp:52] Using GPU
E0201 11:35:23.886492 10779 extract_features.cpp:58] Using Device_id=0
processing 0
A total of 945 images.
terminate called after throwing an instance of 'boost::python::error_already_set'
Aborted (core dumped)

=our environment=
ubuntu16.04 + cuda8, (nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04)

yokattame revision:
  commit 1e88352569c4f4760be9b4509ccfed271c4805b6
  Author: yokattame <yokatta.me@gmail.com>
  Date:   Fri Jul 7 23:17:17 2017 +0800

caffe-master revision:
  commit e963ef4eff86f07b67a23dfffc57f7e918959bd8
  Author: Przemysaw Dolata <snowball91b@gmail.com>
  Date:   Wed Jan 3 10:21:03 2018 +0100

protobuf3.5.1.1-0: downloaded deb images from below
   https://launchpad.net/~maarten-fonville/+archive/ubuntu/protobuf

Thanks in advance.

**Comment by kotabe-sh** [comment]
Sorry, I got double check the issues here, I found out the solution. 
Thanks

**Comment by wudan08** [comment]
excuse me ,I have the same problem ,I want to know how do you solution this problem.Thanks

**Comment by kotabe-sh** [comment]
It was long time ago, but  I guess, in file SpindleNet/models/spindlenet/spindlenet_test.prototxt, 
the line should be replaced like below.
before:    'root_folder': 'external/exp/datasets/${dataset}/‘
after:   'root_folder': ''

**Comment by wudan08** [comment]
Thank you very much .I have solved this problem.Thanks

At 2018-08-24 14:28:16, "kotabe-sh" <notifications@github.com> wrote:


It was long time ago, but I guess, in file SpindleNet/models/spindlenet/spindlenet_test.prototxt,
the line should be replaced like below.
before: 'root_folder': 'external/exp/datasets/${dataset}/‘
after: 'root_folder': ''
