### ISSUE TITLE
ask for environment version set

### ISSUE THREAD

**Issue by tony36486** [yokattame/SpindleNet#16]
hi, 
I want to know your environment version like python version, ubuntu version, cuda and cudnn version.
ths!

**Comment by tony36486** [comment]
> hi,
> I want to know your environment version like python version, ubuntu version, cuda and cudnn version.
> ths!

I success with following setting:
ubuntu 16.04
Nvidia Driver - 384
CUDA® Toolkit 8.0.
cuDNN v6.0.  
Aanconda 2 - python 2.7
Matlab 2014b
OpenCV 3.3

**Comment by swg209** [comment]
@tony36486  Hello, I 'd like to know how to start to set the environment, since I am unfamilary with caffe.Thanks .
