### ISSUE TITLE
where is the layer type 'PYTHON'?

### ISSUE THREAD

**Issue by xuyunlu1030** [yokattame/SpindleNet#3]
I am very interest in your method and reading your code, but I can't find the 'Python' type layer as:

layer {
  name: "data/spindle"
  type: "Python"
  top: "data"
  top: "label"
  top: "headbox"
  top: "bodybox"
  top: "legbox"
  top: "rarmbox"
  top: "larmbox"
  top: "rlegbox"
  top: "llegbox"
  python_param {
    module: "roi_data_layer"
    layer: "RoiDataLayer"
    param_str: "{'source': 'external/exp/datalists/jstl_10/train_p.txt', 'root_folder': '', 'batch_size': 100, 'new_height': 96, 'new_width': 96, 'shuffle': True, 'mirror': True, 'mean_value': [103.939,116.779,123.68], 'region_num': 7, 'region_scale': True}"
  }
}

Can you help me with it?

**Comment by xuyunlu1030** [comment]
Sorry, I am not familiar with pycaffe. I understand now. Thanks for your code.

**Comment by lijiaqi** [comment]
@xuyunlu1030 I meet the same problem with yours. How do you solve it? 
Where can I find the Python layer file "roi_data_layer.py"?

**Comment by YunpengZhai** [comment]
I meet the same problem with yours. How do you solve it? Thanks very much!

**Comment by Cooperzs** [comment]
I meet the same problem with yours. How do you solve it?
Where can I find the Python layer file "roi_data_layer.py"?

**Comment by Cooperzs** [comment]
I meet the same problem with yours. How do you solve it? Thanks very much!
