### ISSUE TITLE
"roi_data_layer.py"  is missing for the training  process of seven body regions

### ISSUE THREAD

**Issue by lijiaqi** [yokattame/SpindleNet#4]
It seems that "roi_data_layer.py"  is missing for the training  process of seven regions. 
Could you provide that?

For example, for head region:
'python_param {
    **module: "roi_data_layer"
    layer: "RoiDataLayer"**
    param_str: ...
  }'

**Comment by wenjie710** [comment]
I have the same problem. I got error message like this, "ImportError: No module named roi_data_layer".

**Comment by lijiaqi** [comment]
Problem solved!

In fact, the author implement `roi_data_layer` in his own caffe. But he didn't mention it in this repository.

You can find `roi_data_layer.py` in https://github.com/yokattame/caffe/blob/master/python/roi_data_layer.py
