### ISSUE TITLE
How to use the test script?

### ISSUE THREAD

**Issue by xuyunlu1030** [yokattame/SpindleNet#5]
When I run ./scripts/test.sh, it shows error "terminate called after throwing an instance of 'boost::python::error_already_set", it seems the problem with the initialization with the first layer, but I do not have any idea about the specific problem. Do you know what is the wrong with it?

**Comment by yutuofish2** [comment]
I meet with exactly the same problem ... The error occurs when running

${CAFFE_DIR}/build/tools/extract_features \
      ${trained_model} ${tmp_model} ${blob},label \
      ${result_dir}/${subset}_features_lmdb,${result_dir}/${subset}_labels_lmdb \
      ${num_iters} lmdb GPU 0

**Comment by lijiaqi** [comment]
I got the same error ```terminate called after throwing an instance of 'boost::python::error_already_se```.

Have you solved it?

**Comment by xuyunlu1030** [comment]
Yes, I have solved it since the error is the problem with input data path in your prototxt, please check it and see if it can help.

**Comment by lijiaqi** [comment]
@xuyunlu1030 Could you share more details about that?  Thank you.

**Comment by Smellly** [comment]
@ljqcava ，replace ``` 'root_folder': 'external/exp/datasets/${dataset}/'``` with  ``` 'root_folder': '' ``` in ```models/spindlenet/spindlenet_test.prototxt``` solved my problem.
